ln -s custom_components/hitachi_yutaki/translations .
ln -s custom_components/hitachi_yutaki/__init__.py .
ln -s custom_components/hitachi_yutaki/binary_sensor.py .
ln -s custom_components/hitachi_yutaki/climate.py .
ln -s custom_components/hitachi_yutaki/config_flow.py .
ln -s custom_components/hitachi_yutaki/const.py .
ln -s custom_components/hitachi_yutaki/coordinator.py .
ln -s custom_components/hitachi_yutaki/manifest.json .
ln -s custom_components/hitachi_yutaki/number.py .
ln -s custom_components/hitachi_yutaki/select.py .
ln -s custom_components/hitachi_yutaki/sensor.py .
ln -s custom_components/hitachi_yutaki/switch.py .
