name = "hitachi-telemetry"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "hitachi-telemetry-archive"

[[hyperdrive]]
binding = "DB"
id = "6022ba5b4aa84149bced9823002142d7"
